# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdg < Formula
  desc ""
  homepage "https://software.es.net/gdg"
  version "0.4.0"
  depends_on :macos

  on_macos do
    url "https://github.com/safaci2000/gdg/releases/download/v0.4.0/gdg_Darwin_all.tar.gz"
    sha256 "fa39f4b7ee13019bdcef721f01b752d7f31273778168766b774a94896f886194"

    def install
      bin.install "gdg"
    end
  end
end
