# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdg < Formula
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting local filesystem, s3, gcs, azure, and other S3 compatible endpoints."
  homepage "https://software.es.net/gdg"
  version "0.4.6"
  depends_on :macos

  on_macos do
    url "https://github.com/safaci2000/gdg/releases/download/v0.4.6/gdg_Darwin_all.tar.gz"
    sha256 "a24c5f4f8efcfb3a78103b74e55ac30401f9138ce1f2384e02f09a5bba9493c3"

    def install
      bin.install "gdg"
    end
  end
end
